enum RequestMethod {
  POST = 'POST',
  PATCH = 'PATCH',
  GET = 'GET',
}

const NAVIGATION_PREFIX = 'NAVIGATION_';

const STATUS_NO_AUTH = 'STATUS_NO_AUTH';
const STATUS_AUTHED = 'STATUS_AUTHED';

//SCREEN
const LAUNCH_SCREEN = `${NAVIGATION_PREFIX}LAUNCH_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;
const SIGNUP_SCREEN = `${NAVIGATION_PREFIX}SIGNUP_SCREEN`;
const HOME_SCREEN = `${NAVIGATION_PREFIX}NAVIGATION_HOME_SCREEN`;

const NAVIGATION_ROOT_WITH_EPIC = 'NAVIGATION_ROOT_WITH_EPIC';
const NAVIGATION_ROOT_SUCCESS = 'NAVIGATION_ROOT_SUCCESS';

export {
  RequestMethod,

  LOGIN_SCREEN,
  HOME_SCREEN,
  LAUNCH_SCREEN,
  SIGNUP_SCREEN,

  NAVIGATION_ROOT_WITH_EPIC,
  NAVIGATION_ROOT_SUCCESS,
  STATUS_NO_AUTH,
  STATUS_AUTHED
}